export const BOOK_LIST_REQUEST='BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS='BOOK_LIST_SUCCES';
export const BOOK_LIST_FAIL='BOOK_LIST_FAILS';
export const BOOK_DETAILS_REQUEST='BOOK_DETAILS_REQUEST';
export const BOOK_DETAILS_SUCCESS='BOOK_DETAILS_SUCCESS';
export const BOOK_DETAILS_FAIL='BOOK_DETAILS_FAIL';

// Cart Constant
export const CART_ADD_ITEM='CART_ADD_ITEM';
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING='CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT='CART_SAVE_PAYMENT';

//User Constant

export const USER_SIGIN_REQUEST = "USER_SIGIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS= "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// BOOK SAVE constant
export const BOOK_SAVE_REQUEST='BOOK_SAVE_REQUEST';
export const BOOK_SAVE_SUCCESS='BOOK_SAVE_SUCCESS';
export const BOOK_SAVE_FAIL='BOOK_SAVE_FAIL';

// BOOK DELETE constant
export const BOOK_DELETE_REQUEST='BOOK_DELETE_REQUEST';
export const BOOK_DELETE_SUCCESS='BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_FAIL='BOOK_DELETE_FAIL';