apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: akshat1608/frontend-app
        ports:
        - containerPort: 3000

---
 
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
spec:
  type: LoadBalancer
  selector:
    app: frontend-app
  ports:
  - port: 3000
    targetPort: 3000

